"""
Evaluation for Wikipedia experiment: Flat RAG vs GraphRAG.
Calculates per-hop accuracy and gap analysis.
"""

import json
import logging
import csv
from pathlib import Path
from typing import Any

from src.utils.llm_client import TRACKER
from src.evaluate import judge_answer, GPT4O_MINI_INPUT_PRICE_PER_1M, GPT4O_MINI_OUTPUT_PRICE_PER_1M, EMBED_SMALL_PRICE_PER_1M
from src.flat_rag_wiki import build_flat_index_wiki, query_flat_rag_wiki
from src.graph_rag_wiki import query_graph_rag_wiki

# Config
ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_PATH = ROOT / "data" / "wiki_questions.json"
OUTPUT_DIR = ROOT / "outputs"
CSV_PATH = OUTPUT_DIR / "benchmark_results_wiki.csv"
COST_PATH = OUTPUT_DIR / "cost_analysis_wiki.md"

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger(__name__)

def run_evaluation_wiki():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    with QUESTIONS_PATH.open(encoding="utf-8") as fh:
        questions = json.load(fh)
    
    logger.info("Building Wikipedia Flat RAG index...")
    collection = build_flat_index_wiki()
    
    results = []
    for q in questions:
        qid = q["id"]
        question = q["question"]
        q_type = q["type"]
        hops = q["hops"]
        ground_truth = q["ground_truth"]
        
        logger.info("=" * 60)
        logger.info("Q%d [%d-hop]: %s", qid, hops, question)
        
        # --- Flat RAG ---
        flat_res = query_flat_rag_wiki(question, collection=collection)
        # --- GraphRAG ---
        graph_res = query_graph_rag_wiki(question)
        
        # --- Judge ---
        flat_judge = judge_answer(question, q_type, ground_truth, flat_res["answer"])
        graph_judge = judge_answer(question, q_type, ground_truth, graph_res["answer"])
        
        results.append({
            "id": qid,
            "question": question,
            "type": q_type,
            "hops": hops,
            "ground_truth": ground_truth,
            "flat_answer": flat_res["answer"],
            "graph_answer": graph_res["answer"],
            "flat_correct": flat_judge["correct"],
            "graph_correct": graph_judge["correct"],
            "flat_tokens": flat_res["tokens"],
            "graph_tokens": graph_res["tokens"],
            "flat_latency_ms": flat_res["latency_ms"],
            "graph_latency_ms": graph_res["latency_ms"],
        })
        
    return results

def save_and_report(results):
    # Save CSV
    fields = results[0].keys()
    with CSV_PATH.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        writer.writerows(results)
    
    # Calculate per-hop stats
    hop_stats = {}
    for r in results:
        h = r["hops"]
        stats = hop_stats.setdefault(h, {"total": 0, "flat": 0, "graph": 0})
        stats["total"] += 1
        if r["flat_correct"]: stats["flat"] += 1
        if r["graph_correct"]: stats["graph"] += 1
        
    print("\n" + "=" * 70)
    print("WIKIPEDIA BENCHMARK SUMMARY")
    print("=" * 70)
    print(f"{'Hops':<6} | {'Flat Acc':<12} | {'Graph Acc':<12} | {'Gap':<6}")
    print("-" * 70)
    
    table_lines = []
    for h in sorted(hop_stats.keys()):
        s = hop_stats[h]
        f_acc = s["flat"] / s["total"]
        g_acc = s["graph"] / s["total"]
        gap = g_acc - f_acc
        print(f"{h:<6} | {f_acc:>11.1%} | {g_acc:>11.1%} | {gap:>+5.1%}")
        table_lines.append(f"| {h} | {s['flat']}/{s['total']} | {s['graph']}/{s['total']} | {gap:+.1%} |")

    # Cost report
    by_stage = TRACKER.tokens_by_stage()
    total_cost = sum(
        (s.get("prompt", 0) / 1e6 * GPT4O_MINI_INPUT_PRICE_PER_1M) +
        (s.get("completion", 0) / 1e6 * GPT4O_MINI_OUTPUT_PRICE_PER_1M)
        for s in by_stage.values()
    )
    
    report = [
        "# Wikipedia Experiment Cost Analysis",
        "",
        "## Per-Hop Accuracy",
        "",
        "| hops | flat correct / total | graph correct / total | gap (graph - flat) |",
        "|------|----------------------|-----------------------|--------------------|",
    ] + table_lines + [
        "",
        f"## Total Token Usage: {TRACKER.total_tokens():,}",
        f"## Total Estimated Cost: ${total_cost:.4f} USD",
        "",
        "---",
        "*Generated by evaluate_wiki.py*"
    ]
    COST_PATH.write_text("\n".join(report), encoding="utf-8")

if __name__ == "__main__":
    results = run_evaluation_wiki()
    save_and_report(results)
